### PR TITLE
Fix Missing HTTP Header

### PR DESCRIPTION
**Pull request by LunaPg**
Finding a bug on integration tests.

Gbfs servers tends to returns a 403 error if we don't pass header.

I fix the issue by passing an entire request object to the `https | http .get` method to avoid get Forbidden error.

The url passed to the http is now parsed properly and handle by node `url` core module.

- [x]  Linter Passed
- [x] Tests Passed

### CODE REVIEW

**Comment by mnkhouri** [comment]
Hi @LunaPg , thanks for the contribution! Looks great. Would you mind providing an example gbfs server I can test this out against where the server needs the User-Agent header?

**Comment by LunaPg** [comment]
> Hi @LunaPg , thanks for the contribution! Looks great. Would you mind providing an example gbfs server I can test this out against where the server needs the User-Agent header?

Hi  @mnkhouri , I just added a test with the gbfs server I had trouble with.
I let you review on more time :)

**Comment by mnkhouri** [comment]
Thanks for adding the test!

**Comment by mnkhouri** [comment]
Published to npm as v0.8.1

**Pull request merged**
